app = "fracture-server"
primary_region = "iad"

[build]
  dockerfile = "server/Dockerfile"

[http_service]
  internal_port = 3001
  force_https = true

[[services]]
  protocol = "tcp"
  internal_port = 3001
  processes = ["app"]

  [services.concurrency]
    type = "connections"
    hard_limit = 100
    soft_limit = 80

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1
